// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/_locales/en/messages.json"
    | "/_locales/zh_CN/messages.json"
    | "/background.js"
    | "/docs/whats-new/v1.3.md"
    | "/docs/whats-new/v1.4.md"
    | "/docs/whats-new/v1.5.md"
    | "/docs/whats-new/v1.6.md"
    | "/docs/whats-new/v1.7.md"
    | "/icon/128.png"
    | "/icon/16.png"
    | "/icon/32.png"
    | "/icon/48.png"
    | "/images/cu-logo.png"
    | "/images/db-logo.png"
    | "/native-messaging/MySquad Native Messaging Installer.dmg"
    | "/sidepanel.html"
    | "/wxt.svg"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime extends Runtime.Static {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
